version: "2"
services:
  api:
    build:
      context: ../old-api
      dockerfile: Dockerfile
    command: nodemon -x "babel-node src/server"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=@@@@@@@@
      - RETHINKDB_HOST=rethinkdb
      - RETHINKDB_PORT=28015
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - GCLOUD_PROJECT=instant-matter-785
      - GCLOUD_PUBSUB_TOPIC=dal_local
      - GCLOUD_PUBSUB_DISABLED=false
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/credentials.json
      - PUBSUB_EMULATOR_HOST=pubsub:8344
    volumes:
      - "../old-api/src:/opt/app/src"
      - "./credentials.json:/credentials/credentials.json"
    links:
      - rethinkdb
      - elasticsearch
      - redis
      - kdf
      - pubsub
    ports:
      - "12345:12345"
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
  elasticsearch:
    image: asia.gcr.io/instant-matter-785/elasticsearch_ik:2.3.5
    ports:
      - "9200:9200"
  redis:
    image: redis
    ports:
      - "6379:6379"
  initial:
    image: asia.gcr.io/instant-matter-785/meepshop-api-initial:2.2.1
    environment:
      - DAL_URL=http://api:12345
      - UPDATE_VERSION=latest
      - USER_NAME=meepshop
      - USER_PASSWORD=meep123456
      - SERVICE_NAME=meepshop
    links:
      - api
    ports:
      - "8888:15264"
  kdf:
    image: asia.gcr.io/instant-matter-785/kdf:0.1.3
    environment:
      - SECRET=1234
    ports:
      - "9999:8888"
  appdash_server:
    image: asia.gcr.io/instant-matter-785/appdash_server:0.1.1
    environment:
      - APPDASH_PORT=8700
      - COLLECTOR_PORT=8701
    ports:
      - "8700:8700"
      - "8701:8701"
  input:
    # command: go run main.go job.go worker.go
    # build:
    #   context: /Users/nukr/workspace/gocode/src/github.com/nukr/input
    #   dockerfile: Dockerfile.dev
    image: asia.gcr.io/instant-matter-785/input:3.0.28
    links:
      - elasticsearch
      - pubsub
    environment:
      - SERVER_ESHOST=elasticsearch
      - SERVER_ESPORT=9200
      - SERVER_PROJECT=instant-matter-785
      - SERVER_TOPIC=dal_local
      - SERVER_SUBSCRIPTION=input_es_local
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/credentials.json
      - PUBSUB_EMULATOR_HOST=pubsub:8344
    volumes:
      - "/Users/nukr/workspace/gocode/src/github.com/nukr/input:/go/src/github.com/nukr/input"
      - "./credentials.json:/credentials/credentials.json"
  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port 0.0.0.0:8344
    ports:
      - "8344:8344"
