version: "2"
services:
  api:
    build:
      context: ../old-api
      dockerfile: Dockerfile
    entrypoint: dockerize -timeout 60s -wait tcp://rethinkdb:28015 -wait tcp://elasticsearch:9200 /opt/app/bin/start.sh
    environment:
      - NODE_ENV=development
      - JWT_SECRET=@@@@@@@@
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - REDIS_HOST=redis
      - ELASTICSEARCH=elasticsearch:9200
    volumes:
      - "../old-api/src:/opt/app/src"
    links:
      - rethinkdb
      - elasticsearch
      - redis
    ports:
      - "12345:12345"
  rethinkdb:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes_from:
      - rethinkdb_data
  rethinkdb_data:
    image: asia.gcr.io/instant-matter-785/rethinkdb-data:0.1.1
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
  redis:
    image: redis
    ports:
      - "6379:6379"
