api:
  build: ../api
  environment:
    - NODE_ENV=development
    - JWT_SECRET=@@@@@@@@@@@
  volumes:
    - "../api/src:/opt/app/src"
  links:
    - rethinkdb
    - elasticsearch
    - redis
  ports:
    - "80:12345"
rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080"
elasticsearch:
  image: elasticsearch
redis:
  image: redis
  ports:
    - "6379:6379"
logstash:
  image: nukr/logstash
  links:
    - rethinkdb
    - elasticsearch
