api:
  image: asia.gcr.io/instant-matter-785/dal:latest
  environment:
    - NODE_ENV=production
    - JWT_SECRET=@@@@@@@@@@@
  links:
    - rethinkdb
    - elasticsearch
    - redis
  ports:
    - "80:12345"
rethinkdb:
  image: rethinkdb
elasticsearch:
  image: elasticsearch
redis:
  image: redis
input:
  image: asia.gcr.io/instant-matter-785/input:latest
  links:
    - rethinkdb
    - elasticsearch
